In [ ]:
#import modules for analyzing ,plotting, and formatting
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime
import seaborn as sns


In [ ]:
merged_400_800 = pd.read_csv("merged_400m_800m_df.csv")

In [ ]:
#import sklearn and relevant packages
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

#separate datasets for the model
#here the model is split 67/33
m400_800_train, m400_800_test = train_test_split(merged_400_800, test_size=0.33, random_state=0)

#gl means grade level
#for this model we will use 400/800m times and grade level
gl_400_800_train = m400_800_train[['400 Meters', '800 Meters', 'Grade Level']]
gl_400_800_test = m400_800_test[['400 Meters', '800 Meters', 'Grade Level']]


In [ ]:
#here we separate the features and labels. The features used are the 400m times as well as the grade leve
# this calls for dropping the 800m column for the features df
#next I select only the 800m column for the label df
features_400_train = gl_400_800_train.drop('800 Meters', axis=1)
label_train = gl_400_800_train['800 Meters'].copy()

#same steps are repeated for the test df
features_400_test = gl_400_800_test.drop('800 Meters', axis=1)
label_test = gl_400_800_test['800 Meters'].copy()

In [ ]:
features_400_train

400 Meters Grade Level
1480       60.24  10th Grade
1478       58.08   9th Grade
966        51.15  12th Grade
471        60.66  12th Grade
1199       62.84  12th Grade
...          ...         ...
763        60.84  10th Grade
835        54.98  10th Grade
1216       91.47   9th Grade
559        59.54  10th Grade
684        60.94  11th Grade

[1045 rows x 2 columns]

In [ ]:
#regression models require numeric data, this means that we have to convert variables from a categorical feature to a binary one.
#grade level is converted to 0s and 1s
# get dummies turned all non-numeric to numeric.
dummy_400_train = pd.get_dummies(features_400_train)

#after converting the grade level column, we reindex the df
dummy_400_train = dummy_400_train.reindex(columns=dummy_400_train.columns, fill_value=0)
features_400_train = dummy_400_train[['400 Meters', 'Grade Level_9th Grade', 'Grade Level_10th Grade', 'Grade Level_11th Grade', 'Grade Level_12th Grade']]
features_400_train

#the same steps are repeated for the test df
dummy_400_test = pd.get_dummies(features_400_test)

dummy_400_test = dummy_400_test.reindex(columns=dummy_400_test.columns, fill_value=0)
features_400_test = dummy_400_test[['400 Meters', 'Grade Level_9th Grade', 'Grade Level_10th Grade', 'Grade Level_11th Grade', 'Grade Level_12th Grade']]
features_400_test

400 Meters  Grade Level_9th Grade  Grade Level_10th Grade  \
319        64.14                      0                       0   
1041       54.84                      0                       0   
798        54.44                      0                       1   
579        50.50                      0                       0   
414        53.14                      0                       0   
...          ...                    ...                     ...   
971        56.53                      0                       0   
1417       54.90                      1                       0   
737        65.74                      0                       1   
477        57.24                      0                       0   
1399       62.30                      0                       0   

      Grade Level_11th Grade  Grade Level_12th Grade  
319                        1                       0  
1041                       1                       0  
798                        0                       0  
579                        0                       1  
414                        0                       1  
...                      ...                     ...  
971                        0                       1  
1417                       0                       0  
737                        0                       0  
477                        1                       0  
1399                       1                       0  

[515 rows x 5 columns]

In [ ]:
#here I am selecting the runners with times between 59 and 60 seconds in the 400m
#next I am finding those same runners in the labeled data (800m times)
#I do this as a simple measure so that I can compare the single test predicitions below, and get 
# a sense of which model is predicting closes to what we expect a runner to run. 

times = features_400_train[(features_400_train['400 Meters'] > 59) & (features_400_train['400 Meters'] < 60)]
label_train[times.index].mean()

138.2977777777778

In [ ]:
# I used a small definition from Intro to machine learning to display the scores from the cross val.
#this code will be used later to display the scores from cross val cv
def display_scores(scores):
  print('Scores:', scores)
  print('Mean:', scores.mean()),
  print('Standard Deviation:', scores.std())


Here we have the data processed and formatted to run multiple ML models.
These will be LinearRegression, Decision Tree Regression, and Forest Regression.

Our main measure of the data is the RMSE. This function compares the values of the labels to the predictions. We compare this value for all the training data and choose a model that works best before we use the test data.

In [ ]:
#after preparing the data we are ready to create the linear regression instance
# and train the model with out data

linreg = LinearRegression()
linreg.fit(features_400_train, label_train)

#here we are importing another regression model to test the difference,
# and checking is a more powerful model will produce better results.
#we fit this model and predict on our training data as we did before.

tree_reg = DecisionTreeRegressor()
tree_reg.fit(features_400_train, label_train)

#the most powerful model used in this project
forest_reg = RandomForestRegressor()
forest_reg.fit(features_400_train, label_train)

#we import the one more regression model which will be the most powerful
#the steps will be the same as before

forest_reg = RandomForestRegressor()
forest_reg.fit(features_400_train, label_train)

RandomForestRegressor()

After creating an instance for each regression model, we fit each of them on the training data. 

After each fit we predict on training data and compare the training labels to analyze the accuracy.


In [ ]:
#after training we check out model by predicting using out training data
#we compare out predictions on training data vs. the labels and study the difference
# RMSE is the Root Mean Square Error, which measures the difference between predicted values and the labels. 
# this measure is common and works well with regression models.

train_pred = linreg.predict(features_400_train)
lin_mse = mean_squared_error(label_train, train_pred)
lin_rmse = np.sqrt(lin_mse)
print('linreg RMSE: ', lin_rmse)

linreg RMSE:  8.776397328177701


In [ ]:
#predicting with the Decision Tree Regression 
tree_pred = tree_reg.predict(features_400_train)
tree_mse = mean_squared_error(label_train, tree_pred)
tree_rmse = np.sqrt(tree_mse)
print('decision tree RMSE: ', tree_rmse)

decision tree RMSE:  4.012482225809878


In [ ]:
#prediction with Forest Regression
forest_pred = forest_reg.predict(features_400_train)
forest_mse = mean_squared_error(label_train, forest_pred)
forest_rmse = np.sqrt(forest_mse)

print('forest RMSE:',  forest_rmse)

forest RMSE: 5.061685064962189


In [ ]:
#here is a small test using a runner with a 60 second 400m.
# the number 1 represents a grade level.
#using this we can run a simple test to see how acurate a single prediction is.
#the array corresponds to 400m time, 9th grade, 10th grade, 11th grade, and 12th grade (in this order).

test_arr = np.array([52,0,0,0,1])
test_arr = test_arr.reshape(1,-1)

#predicting a single result with linreg
test_pred_lin = linreg.predict(test_arr)
test_pred_lin

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([123.03373997])

In [ ]:
#here we run the same test as before, with a single sample, and compare how the decision tree predicts.
#although the decision tree has a lower RMSE than linreg, the prediction is futher off what we would expect.
# this shows that the decision tree likely is overfitting the data

#predicting a single result with Decison tree
test_pred_tree = tree_reg.predict(test_arr)
test_pred_tree

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([115.25])

In [ ]:
# predicting a single result with forest regression 
test_pred_forest = forest_reg.predict(test_arr)
test_pred_forest

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([121.8829])

In [ ]:
# the same cross val is run using linear regression

lin_scores = cross_val_score(linreg, features_400_train, label_train, 
                         scoring='neg_mean_squared_error', cv=10)

#compared to the original linreg, the mean here is marginally better, but it is still insightful to check 
#the original values and compare.

lin_rmse_scores = np.sqrt(-lin_scores)
display_scores(lin_rmse_scores)

Scores: [ 6.27144725  8.72056697  8.18682836 10.30698787  9.52955247 10.25102466
  7.28613984  8.20567994  8.99320148  9.74589946]
Mean: 8.749732829168252
Standard Deviation: 1.2343570588323662


In [ ]:
#here I import cross_val_score which will allow me to test the decision tree 
#and improve how it fits by taking small chunks of the data and training on each chunk
# this results in a better fitting.

tree_scores = cross_val_score(tree_reg, features_400_train, label_train, 
                         scoring='neg_mean_squared_error', cv=10)

# displaying the scors shows a larger mean
#this is expected because before, the data was being overfit
tree_rmse_scores = np.sqrt(-tree_scores)
display_scores(tree_rmse_scores)

Scores: [11.55466307 10.89551063  9.86414704 14.63550698 11.61899021 13.17262269
 11.19044967 10.88550466 13.18897704 13.26115961]
Mean: 12.026753160450498
Standard Deviation: 1.3907085722433408


In [ ]:
#just as with the decision tree, randome forest was likely overfitting the training data
# when using crossval we see that the mean is a amost twice as bad
# still, this model produces the best results
#this is also expected because this model is more powerful 

forest_scores = cross_val_score(forest_reg, features_400_train, label_train, 
                         scoring='neg_mean_squared_error', cv=10)

forest_rmse_scores = np.sqrt(-forest_scores)
display_scores(forest_rmse_scores)

Scores: [ 8.12751438  9.53132493  9.38010474 12.08666266 10.28338023 11.57416809
  9.33913006  9.13012512 11.05686155 11.90547668]
Mean: 10.24147484363784
Standard Deviation: 1.2798721604933723


In [ ]:
#after going through the models, we import one last package, GridSearchCV
#this sorts through many parameters and returns the best one.

param_grid = [
    {'n_estimators': [3,10,30], 'max_features': [2,4,6,8]},
    {'bootstrap': [False], 'n_estimators': [3,10], 'max_features': [2,3,4]}
]
grid_search_forest = GridSearchCV(forest_reg, param_grid, cv=5,
                           scoring='neg_mean_squared_error',
                           return_train_score=True)

#here the grid search model is used to fit the training data
#next we print out the best params and best estimators
grid_search_forest.fit(features_400_train, label_train)
print(grid_search_forest.best_params_)
print(grid_search_forest.best_estimator_)

{'max_features': 6, 'n_estimators': 30}
RandomForestRegressor(max_features=6, n_estimators=30)


In [ ]:
#here the features and estimators are zip together with the scores
#then they are printed out so we can see which returned the best and the range of values 
#that result from the changes in parameters

cv_res = grid_search_forest.cv_results_

for mean_score, params in zip(cv_res['mean_test_score'], cv_res['params']):
  print(np.sqrt(-mean_score), params)

11.232216320694521 {'max_features': 2, 'n_estimators': 3}
11.077568294006781 {'max_features': 2, 'n_estimators': 10}
10.751221404970853 {'max_features': 2, 'n_estimators': 30}
11.246824481809476 {'max_features': 4, 'n_estimators': 3}
10.711158774950837 {'max_features': 4, 'n_estimators': 10}
10.427061155542571 {'max_features': 4, 'n_estimators': 30}
10.84843076061946 {'max_features': 6, 'n_estimators': 3}
10.431766477296936 {'max_features': 6, 'n_estimators': 10}
10.329417697113794 {'max_features': 6, 'n_estimators': 30}
11.02029906461735 {'max_features': 8, 'n_estimators': 3}
10.403029916142899 {'max_features': 8, 'n_estimators': 10}
10.348698856534417 {'max_features': 8, 'n_estimators': 30}
12.342086014648514 {'bootstrap': False, 'max_features': 2, 'n_estimators': 3}
12.268871560313263 {'bootstrap': False, 'max_features': 2, 'n_estimators': 10}
11.949327161988641 {'bootstrap': False, 'max_features': 3, 'n_estimators': 3}
12.140728608954237 {'bootstrap': False, 'max_features': 3, 'n_e

In [ ]:
#lastly we isolate the best estimators from the model
#we then predict the TEST data and compare to the test labels
final_model = grid_search_forest.best_estimator_
final_pred = final_model.predict(features_400_test)

final_mse = mean_squared_error(label_test, final_pred)
final_rmse = np.sqrt(final_mse)
print(final_rmse)

9.765167654429185


In [ ]:
test_pred = final_model.predict(test_arr)
print(test_pred)

[122.5692]


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
